spring.application.name=Wao_be

# =====================
# DataSource - MySQL
# =====================
spring.datasource.url=jdbc:mysql://localhost:3306/wao
spring.datasource.username=root
spring.datasource.password=liam252004
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =====================
# JPA / Hibernate
# =====================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# =====================
# Server
# =====================
server.port=8080

# ===== CLOUDINARY =====
cloudinary.cloud-name=du5pmld46
cloudinary.api-key=591491888414923
cloudinary.api-secret=GGULQN42s7Y7i0i5YadNawQSnp8

# ===== OPENROUTER =====
openrouter.base-url=https://openrouter.ai/api/v1/chat/completions
openrouter.api-key=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
openrouter.model=nvidia/nemotron-3-super-120b-a12b:free
openrouter.site-url=http://localhost:8080
openrouter.app-name=Wao Backend
openrouter.connect-timeout-ms=10000
openrouter.read-timeout-ms=60000
openrouter.max-tokens=500
openrouter.temperature=0.7
openrouter.max-history-messages=20


